---
- name: Role test playbook
  hosts: all
  gather_facts: true
  roles:
    - role: app
      vars:
        app_env_variables:
          NUM_MACHINES: 5
          BASE_PORT: 3000
          BASE_WS_PORT: 8080
          BASE_APP_PORT: 8000
          NETWORK_SUBNET: 10.89.2.0/24
          DELAY: 200
          SIZE: 40
          BASE_MONGO_PORT: 27018
        app_modules:
          explorer: true
          watcher: true
