---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch CouchDB's app version on git
      ansible.builtin.get_url:
        url: "https://github.com/AxelDumon/V2/archive/refs/heads/CouchDB.zip"
        dest: /tmp/V2.zip
        mode: '0644'
      register: fetch_couchdb_version
    - name: Unzip CouchDB app version
      ansible.builtin.unarchive:
        src: /tmp/V2.zip
        dest: /tmp/
    
    - name: Display fetched CouchDB app version
      ansible.builtin.debug:
        msg: "CouchDB app version fetched to {{ fetch_couchdb_version.dest }}"