app_module_build_dir: /tmp/app/server/build
app_module_src_dir: /tmp/app/server
app_service_name: exploring-agent
app_service_template: exploring-agent.service.j2
app_target_build_dir: /app/server/build
app_target_src_dir: /app/server
user: root
group: root