$ANSIBLE_VAULT;1.1;AES256
30303034663934373463346235666639303832393261373137376165613436373635376663613132
6138613363346638386134643836396639323530626338320a663830383538613930643066383465
34663665663264343430333430633961373564336530306439396635373632396465643837333732
6365316536313436610a636132633931613236663961366537643261343131323032333839623933
34343330336630653063616432313365656235396339376233663131306465373663303163656433
65363534353965373936393434626231313563653361373638316562663436333139306230393331
37666637343662386433643634636463656465336632303438333261383365316632336634303834
30353666333739333665353765303736646261613331336539376231383564613937333634653565
34303964626533663438323462383733326337376237383661666535613532343235
