- name: Clone or update local front repository
  ansible.builtin.git:
    repo: 'git@github.com:AxelDumon/ExplorationToyProblem-LocalFront.git'
    dest: /app/public
    version: "{{ app_version }}"
    update: true
    force: true
    accept_hostkey: true
    key_file: ~/.ssh/ExplorationToyProblem-LocalFront

- name: Clone or update backend repository
  ansible.builtin.git:
    repo: 'git@github.com:AxelDumon/ExplorationToyProblem-Backend.git'
    dest: /app/server
    version: "{{ app_version }}"
    force: true
    update: true
    accept_hostkey: true
    key_file: ~/.ssh/ExplorationToyProblem-Backend

- name: Create .env file for the backend
  tags: app, build, deploy, env
  ansible.builtin.template:
    src: explorer-env.j2
    dest: "/app/{{ item }}/.env"
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  loop:
    - server
    - public

- name: Ensure nodejs and npm are installed
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: present

- name: Clean node_modules directories
  ansible.builtin.file:
    path: /app/{{ item }}/node_modules
    state: absent
  loop:
    - public
    - server

- name: Ensure dependencies are installed globally
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop:
    - concurrently
    - vite

- name: Install dependencies locally
  tags: app, build, deploy
  ansible.builtin.command:
    cmd: npm install
    chdir: /app/{{ item }}
    creates: /app/{{ item }}/node_modules
  loop:
    - public
    - server

- name: Build apps locally
  tags: app, build, deploy
  ansible.builtin.command:
    cmd: npm run build
    chdir: /app/{{ item }}
    creates: /app/{{ item }}/build
  loop:
    - public
    - server


- name: Create service file for exploring agent
  tags: app, build, deploy, systemd
  ansible.builtin.template:
    src: exploring-agent.service.j2
    dest: /etc/systemd/system/exploring-agent.service
    mode: '0644'
    owner: root
    group: root
  register: app_exploring_service_conf
  notify: ReloadSystemd

- name: Install dependencies from lockfile
  tags: app, build, deploy
  community.general.npm:
    ci: true
    path: /app/server
    state: present

- name: Start exploring-agent service
  tags: app, build, deploy
  ansible.builtin.service:
    name: exploring-agent
    enabled: true
    state: started
