---
- name: Restart MongoDB
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true
- name: Reload systemd
  become: true
  ansible.builtin.command:
    cmd: "systemctl daemon-reload"
  listen: reload_systemd
- name: Restart CouchDB
  become: true
  ansible.builtin.service:
    name: "{{ couchdb_service_name }}"
    state: restarted
    enabled: true
  listen: restart_couchdb
