---
- name: Restart MongoDB
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload_systemd
- name: Restart CouchDB
  ansible.builtin.systemd:
    name: couchdb
    state: restarted
  listen: restart_couchdb
