---
- name: Prepare the repositories and build the app
  hosts: localhost
  gather_facts: false
  become: true
  become_user: axel
  tasks:
    - name: Install Git if not present (Debian/Ubuntu)
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure nodejs and npm are installed
      ansible.builtin.package:
        name:
          - nodejs
          - npm
        state: present
      delegate_to: localhost

    - name: Install TypeScript globally if not present
      community.general.npm:
        name: typescript
        global: true
        state: present
      delegate_to: localhost

    - name: Clone or update global front repository
      ansible.builtin.git:
        repo: 'git@github.com:AxelDumon/ExplorationToyProblem-GlobalFront.git'
        dest: /tmp/ExplorationToyProblem-GlobalFront
        version: master
        update: true
        accept_hostkey: true
        key_file: ~/.ssh/id_ed25519.pub

    - name: Clone or update local front repository
      ansible.builtin.git:
        repo: 'git@github.com:AxelDumon/ExplorationToyProblem-LocalFront.git'
        dest: /tmp/ExplorationToyProblem-LocalFront
        version: master
        update: true
        accept_hostkey: true
        key_file: ~/.ssh/id_ed25519.pub

    - name: Clone or update backend repository
      ansible.builtin.git:
        repo: 'git@github.com:AxelDumon/ExplorationToyProblem-Backend.git'
        dest: /tmp/ExplorationToyProblem-Backend
        # Change version to change DB
        # Possible versions : mongodb, couchdb, master
        version: master
        update: true
        accept_hostkey: true
        key_file: ~/.ssh/id_ed25519.pub

    - name: Clean node_modules directories
      ansible.builtin.file:
        path: /tmp/{{ item }}/node_modules
        state: absent
      loop:
        - ExplorationToyProblem-GlobalFront
        - ExplorationToyProblem-LocalFront
        - ExplorationToyProblem-Backend
    
    - name: Install dependencies locally
      tags: app, build, deploy
      ansible.builtin.command:
        cmd: npm install
        chdir: /tmp/{{ item }}
        creates: /tmp/{{ item }}/node_modules
      loop:
        - ExplorationToyProblem-GlobalFront
        - ExplorationToyProblem-LocalFront
        - ExplorationToyProblem-Backend

    - name: Build apps locally
      tags: app, build, deploy
      ansible.builtin.command:
        cmd: npm run build
        chdir: /tmp/{{ item }}
        creates: /tmp/{{ item }}/build
      loop:
        - ExplorationToyProblem-GlobalFront
        - ExplorationToyProblem-LocalFront
        - ExplorationToyProblem-Backend