---
- name: Launch watcher agent application
  hosts: watching_agents
  tasks:
    - name: Start watcher agent
      ansible.builtin.command:
        cmd: npm start
        chdir: /app/global
        creates: /app/global/.lock
      register: start_result
      ignore_errors: true
    - name: Display start result
      ansible.builtin.debug:
        var: start_result.stdout_lines
