---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure SSH service is installed
  ansible.builtin.package:
    name: "openssh-server"
    state: present

- name: Ensure SSH service is enabled and running
  ansible.builtin.service:
    name: "{{ sshd_service }}"
    state: started
    enabled: true

- name: Deploy SSH configuration file
  ansible.builtin.copy:
    src: files/sshd_config.ini
    dest: /etc/ssh/sshd_config
    owner: "root"
    group: "root"
    mode: '0600'
  notify: Restart SSHD

# - name: Add key to authorized_keys
#   ansible.builtin.authorized_key:
#     user: "{{ ansible_user }}"
#     state: present
#     key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
#     manage_dir: false
