---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure SSH service is installed
  ansible.builtin.package:
    name: "{{ sshd_service }}"
    state: present

- name: Ensure SSH service is enabled and running
  ansible.builtin.service:
    name: "{{ sshd_service }}"
    state: started
    enabled: true

- name: Deploy SSH configuration file
  ansible.builtin.copy:
    src: files/sshd_config.ini
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart SSHD