---
- name: Ensure OpenSSH Server is installed
  ansible.windows.win_feature:
    name: OpenSSH.Server
    state: present

- name: Ensure OpenSSH Server is running
  ansible.windows.win_service:
    name: sshd
    start_mode: auto
    state: started

- name: Deploy SSH configuration file
  ansible.builtin.copy:
    src: files/sshd_config.ini
    dest: C:\ProgramData\ssh\sshd_config
    owner: root
    group: root
    mode: 0644

  notify: Restart SSHD